In [2]:
import numpy as np
import pandas as pd


[[2 3 2 9]
 [6 1 8 4]
 [8 9 6 3]]
   col1  col2  col3  col4
0     2     3     2     9
1     6     1     8     4
2     8     9     6     3


In [5]:
values = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(values)
words = ['a', 'b', 'c', 'd']

tfidf_before_keywords = pd.DataFrame(values, columns=words)
print(tfidf_before_keywords)

keywords = ['b', 'c', 'f', 'g', 'h']

# 新しいDataFrameを作成
tfidf = pd.DataFrame()

for col in keywords:
    if col in tfidf_before_keywords.columns:
        tfidf[col] = tfidf_before_keywords[col]
    else:
        tfidf[col] = 0

print(tfidf)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
   a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12
    b   c  f  g  h
0   2   3  0  0  0
1   6   7  0  0  0
2  10  11  0  0  0


In [6]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

# データセットのサンプルを作成
X_train = np.random.rand(1000, 3)
y_train = np.random.randint(2, size=1000)  # 0または1のラベルを持つサンプルデータ

X_test = np.random.rand(100, 3)
y_test = np.random.randint(2, size=100)

# モデルの定義
model = keras.Sequential([
    keras.layers.Dense(128, activation='relu', input_shape=(3,)),  # 入力層
    keras.layers.Dense(2, activation='softmax')  # 2クラス分類のための出力層
])

# モデルのコンパイル
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# モデルのトレーニング
model.fit(X_train, y_train, epochs=10)

# テストデータでの評価
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=2)
print('\nTest accuracy:', test_acc)

# 予測
predictions = model.predict(X_test)
predicted_labels = np.argmax(predictions, axis=1)
print(predicted_labels)


Epoch 1/10
32/32 [==============================] - 1s 2ms/step - loss: 0.6942 - accuracy: 0.4890
Epoch 2/10
32/32 [==============================] - 0s 3ms/step - loss: 0.6923 - accuracy: 0.5050
Epoch 3/10
32/32 [==============================] - 0s 2ms/step - loss: 0.6919 - accuracy: 0.5040
Epoch 4/10
32/32 [==============================] - 0s 2ms/step - loss: 0.6920 - accuracy: 0.5210
Epoch 5/10
32/32 [==============================] - 0s 2ms/step - loss: 0.6916 - accuracy: 0.5230
Epoch 6/10
32/32 [==============================] - 0s 2ms/step - loss: 0.6914 - accuracy: 0.5330
Epoch 7/10
32/32 [==============================] - 0s 1ms/step - loss: 0.6924 - accuracy: 0.5120
Epoch 8/10
32/32 [==============================] - 0s 2ms/step - loss: 0.6912 - accuracy: 0.5100
Epoch 9/10
32/32 [==============================] - 0s 2ms/step - loss: 0.6912 - accuracy: 0.5140
Epoch 10/10
32/32 [==============================] - 0s 2ms/step - loss: 0.6916 - accuracy: 0.5300
4/4 - 0s - loss: 0.